steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image']

images:
  - 'us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image'
