steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image:$SHORT_SHA'
      - '.'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image:$SHORT_SHA'

  # Step 3: Trigger Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--project=enhub-cloud-interns'
      - '--region=us-central1'
      - '--delivery-pipeline=myapp-pipeline'
      - '--images=myapp-image=us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image:$SHORT_SHA'

images:
  - 'us-central1-docker.pkg.dev/enhub-cloud-interns/myapp-docker-repo/myapp-image:$SHORT_SHA'
